# Generated by Django 6.0 on 2025-12-17 11:11

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import treks_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('excerpt', models.TextField(blank=True, help_text='Short description for blog listings', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/', validators=[treks_app.models.validate_image_file_extension])),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='blogs/originals/', validators=[treks_app.models.validate_image_file_extension])),
                ('image_url', models.URLField(blank=True, editable=False, null=True)),
                ('original_image_url', models.URLField(blank=True, editable=False, null=True)),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('map_url', models.URLField(blank=True, help_text='Google Maps URL')),
            ],
            options={
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('booking', 'Booking & Payment'), ('treks', 'Treks & Activities'), ('safety', 'Safety & Equipment'), ('Cancellation & Refund', 'Cancellation & Refund'), ('Payment-Related', 'Payment-Related'), ('Customer-support', 'Customer-Support')], default='general', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='banners/', validators=[treks_app.models.validate_image_file_extension])),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_url', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='safety_icons/', validators=[treks_app.models.validate_image_file_extension])),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='social_icons/', validators=[treks_app.models.validate_image_file_extension])),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
            ],
            options={
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='team/', validators=[treks_app.models.validate_image_file_extension])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms and Conditions', max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopTrek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='toptreks/')),
                ('image_url', models.URLField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.TextField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='treks/', validators=[treks_app.models.validate_image_file_extension])),
                ('duration', models.CharField(help_text="e.g., '2 days, 1 night'", max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult'), ('extreme', 'Extreme')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrekCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Trek Categories',
            },
        ),
        migrations.CreateModel(
            name='TrekImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trek_images/', validators=[treks_app.models.validate_image_file_extension])),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TrekOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='organizers/', validators=[treks_app.models.validate_image_file_extension])),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrekPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='whatsnew/')),
                ('image_url', models.URLField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', validators=[treks_app.models.validate_image_file_extension])),
                ('trek_name', models.CharField(blank=True, help_text='Only required if trek is not selected', max_length=200)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('is_featured', models.BooleanField(default=False)),
                ('trek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='treks_app.trek')),
            ],
        ),
        migrations.AddField(
            model_name='trek',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treks', to='treks_app.trekcategory'),
        ),
        migrations.AddField(
            model_name='trek',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='trek_images', to='treks_app.trekimage'),
        ),
        migrations.CreateModel(
            name='TrekList',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('hero_image', models.CharField(blank=True, max_length=500, null=True)),
                ('duration_days', models.CharField(blank=True, max_length=100, null=True)),
                ('price_start', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('operating_days', models.CharField(blank=True, max_length=200, null=True)),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('highlights', models.TextField(blank=True, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operators', models.ManyToManyField(blank=True, to='treks_app.operator')),
                ('related_treks', models.ManyToManyField(blank=True, to='treks_app.treklist')),
                ('tags', models.ManyToManyField(blank=True, to='treks_app.tag')),
                ('trek_points', models.ManyToManyField(blank=True, to='treks_app.trekpoint')),
            ],
        ),
        migrations.CreateModel(
            name='TrekImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trek_images/', validators=[treks_app.models.validate_image_file_extension])),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='treks_app.treklist')),
            ],
        ),
        migrations.AddField(
            model_name='trek',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treks', to='treks_app.trekorganizer'),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['visit_time'], name='treks_app_v_visit_t_fdf07d_idx'), models.Index(fields=['ip_address'], name='treks_app_v_ip_addr_982555_idx')],
            },
        ),
    ]
