# Generated by Django 6.0 on 2025-12-17 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekimage',
            name='trek',
            field=models.ForeignKey(default='default-trek', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='treks_app.treklist'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TrekImageList',
        ),
    ]
