# Generated by Django 6.0 on 2025-12-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0002_trekimage_trek_delete_trekimagelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treklist',
            name='id',
            field=models.SlugField(editable=False, primary_key=True, serialize=False),
        ),
    ]
