# Generated by Django 6.0 on 2025-12-29 12:00

import treks_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0003_alter_treklist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekimage',
            name='image_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='trekimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trek_images/', validators=[treks_app.models.validate_image_file_extension]),
        ),
    ]
